### ISSUE TITLE
supporting pdf creation

### ISSUE THREAD

**Issue by gidden** [iiasa/message_doc#8]
there are a few issues right now in the latex writing that will need to be updated to support latex writing
- change all unicode characters to their math equivalents (tau, sigma)
- update all linebreaks using `\left.`and `\right.` around line breaks (`\\`)
- fix figure caption indentation

An example of all the lines that need to be fixed are in #7

**Comment by khaeru** [comment]
Two years on (:smile:), we have moved to RTD, which successfully builds the PDF and EPUB versions of the docs:

1. Visit https://message.iiasa.ac.at/global/
2. In the bottom of the sidebar, click “Read the Docs”, then “PDF” under “Downloads”.

Should this (and #7) be closed as stale, and re-opened if there is a need to make specific changes to the PDF version?

**Comment by gidden** [comment]
done and done!
